---
- name: Loops Playbook
  hosts: staging
  become: yes


  tasks:
  - name: Say Hello to ALL
    debug: 
      msg: "Hello {{ item }}"
    loop: 
        - "Nikita"
        - "Sasha"
        - "Petya"
        - "Kolya"


  - name: Loop Until example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: outputmyfile
    delay: 2
    retries: 10
    until: outputmyfile.stdout.find("ZZZZ") == false

  - name: Print final output
    debug: 
      var: outputmyfile.stdout

 # - name: Install many packages
 #    yum: name {{ item }} state= installed
#     with_items:
  #           - python
   #          - mysql-client
